title: "Sneha Sharma"
description: "Academic Profile & Portfolio"
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache

# Navigation bar
nav:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Projects"
    url: /projects/
  - title: "CV"
    url: /cv/
  - title: "Contact"
    url: /contact/
  - title: "Spotify"
    url: https://open.spotify.com/show/3qtyZpV7l2MT9S8bqvv0EO?si=0c507e40e1214ffd
  - title: "Blog"
    url: https://hindibhaashaa.wordpress.com/
  - title: "Slides"
    url: https://docs.google.com/presentation/d/xxxxxxx/edit?usp=sharing  # replace with your link





